### PR TITLE
feat: new email styles

### PR DESCRIPTION
**Pull request by vinckr**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
@vinckr is the report still running? or is it finished? if it is finished should we keep the questionaire in or not?

**Comment by vinckr** [comment]
> @vinckr is the report still running? or is it finished? if it is finished should we keep the questionaire in or not?

sorry yea I would keep the questionaire for at least the Hydra 2.0 release. We just used slack&socials so far, so the survey would reach a lot more people who arent active there.

**Comment by aeneasr** [comment]
ping @vinckr

**Comment by vinckr** [comment]
Can you point me to how to generate the correct stub for testing the email body @aeneasr? I used the output in mailchimp but the formatting seems to be off...

It also seems to be testing against the old version still no matter how I change `changelog.html.expected`.

**Comment by aeneasr** [comment]
You need to run the test, rename changelog.html.tmp to changelog.html.expected, run the test again -> it works

**Comment by vinckr** [comment]
ahh ty, works now :D 
i totally missed the `changelog.html.tmp`

**Pull request merged**
