### PR TITLE
Add key ID to JWT header

### PR DESCRIPTION
**Pull request by znorris**
## Related Issue or Design Document

Relates to issue #144. Being able to lookup the signing key by the key ID is very helpful when using a keystore. This change was originally accepted in PR #145 but was (accidentally?) dropped during some later code reshuffling.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
Thank you! Sorry that this got lost. If you want, you can also add a test for this so that it never regresses again!

**Comment by znorris** [comment]
That's a good idea. @aeneasr Is there an existing test you might point me to as an example?

**Comment by aeneasr** [comment]
https://github.com/ory/cli/blob/d00661e35fb3d04beae249991b3d5094cfca4c10/cmd/cloudx/e2e/cypress/integration/integration.spec.js#L22-L28

Has the code which verifies the JWT, in here you could probably add an assertion for it :)

Here's the script to run the tests:

https://github.com/ory/cli/blob/d00661e35fb3d04beae249991b3d5094cfca4c10/.github/workflows/test-e2e.yml#L41-L49

**Comment by adrianrudnik** [comment]
Just tried to do the tests in branch, as this seems to be a stale PR right now, but the feature is still missing.

Failed to go any further: Seems like I need a project set up for tests only and `npm run test` just fails with `You passed the --record flag but did not provide us your Record Key.`. Digging myself through the github workflows did not help either.

Any advice?

**Review by aeneasr — APPROVED** [review]

**Pull request merged**
